# Site settings
title: Jeongwon Park
baseurl: ""
url: "https://parkgarden.github.io"
google_analytics: # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: Jeongwon Park
  desc: Ph.D. Student <br> E-mail. <a href="mailto:jpark440@asu.edu">jpark440@asu.edu</a> <br> <a href="https://scholar.google.com/citations?user=EAtqHsAAAAAJ&hl=en">Google Scholar</a> |  <a href="https://github.com/parkgarden">Github</a> | <a href="https://orcid.org/0000-0001-9229-9393">ORCID</a> | <a href="https://www.linkedin.com/in/jeongwon-park-a87760202/">LinkedIn</a> | <a href="https://nbviewer.org/github/parkgarden/parkgarden.github.io/blob/master/assets/files/JeongwonPark_CV_05_01_2025.pdf">CV</a> 
  email: jpark440@asu.edu
  selfie: assets/img/Jeongwon Park.jpg

# social
social:
  # email: true
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  # github: parkgarden
  google_plus:
  instagram:
  keybase:
  # linkedin: https://www.linkedin.com/in/jeongwon-park-a87760202/
  pinterest:
  reddit:
  soundcloud:

  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter:
  vimeo:
  wordpress:
  youtube:
  # google_scholar: https://scholar.google.com/citations?hl=ko&authuser=2&user=EAtqHsAAAAAJ
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"
